import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { LoadingProvider } from "@/context/loadingcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  verification: {
    google: "D6VlW_2Vd204Xs_lr_sIlY6jZ0lmynxokc1ezwhOVGo", 
  },
  title: "blog milik jagat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full ">
        <Navbar />
        <LoadingProvider>
        <div className="min-h-screen flex flex-col bg-gray-200  text-black">
        {children}
        </div>
        </LoadingProvider>
        </body>
    </html>
  );
}
